apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fraud-mlops-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # Replace with your actual GitHub repository URL
    repoURL: 'https://github.com/wasimbaari/credit.card-fraud-mlops.git'
    targetRevision: HEAD
    path: infra/kubernetes
    directory:
      recurse: true # Automatically picks up mlflow and kserve subdirectories
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true    # Automatically deletes resources removed from Git
      selfHeal: true # Automatically corrects manual changes made via kubectl
    syncOptions:
      - CreateNamespace=true