import pandas as pd
import numpy as np
import logging

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

class FraudFeatureEngineer:
    def __init__(self):
        # We define constants for the Earth's radius to calculate distances
        self.EARTH_RADIUS_KM = 6371.0

    def haversine_vectorized(self, lat1, lon1, lat2, lon2):
        """Calculates the great-circle distance between two points on Earth."""
        lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])
        
        dlat = lat2 - lat1
        dlon = lon2 - lon1
        
        a = np.sin(dlat / 2.0)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon / 2.0)**2
        c = 2 * np.arcsin(np.sqrt(a))
        return self.EARTH_RADIUS_KM * c

    def extract_time_features(self, df, time_col='trans_date_trans_time'):
        """Extracts cyclical temporal features from transaction timestamps."""
        df[time_col] = pd.to_datetime(df[time_col])
        df['hour'] = df[time_col].dt.hour
        df['day_of_week'] = df[time_col].dt.dayofweek
        
        # Cyclical encoding for hours (keeps 23:00 and 00:00 close together mathematically)
        df['hour_sin'] = np.sin(2 * np.pi * df['hour']/24.0)
        df['hour_cos'] = np.cos(2 * np.pi * df['hour']/24.0)
        
        return df.drop(columns=[time_col, 'hour'])

    def build_features(self, df):
        """Executes the full feature engineering pipeline safely."""
        logging.info("Starting feature engineering pipeline...")
        df = df.copy()

        # 1. Calculate transaction distance
        logging.info("Calculating Haversine distances...")
        if all(col in df.columns for col in ['lat', 'long', 'merch_lat', 'merch_long']):
            df['distance_km'] = self.haversine_vectorized(
                df['lat'], df['long'], df['merch_lat'], df['merch_long']
            )

        # 2. Age calculation
        if 'dob' in df.columns and 'trans_date_trans_time' in df.columns:
            df['dob'] = pd.to_datetime(df['dob'])
            df['trans_date'] = pd.to_datetime(df['trans_date_trans_time'])
            df['customer_age'] = (df['trans_date'] - df['dob']).dt.days // 365
            df = df.drop(columns=['dob', 'trans_date'])

        # 3. Time features
        logging.info("Extracting temporal features...")
        if 'trans_date_trans_time' in df.columns:
            df = self.extract_time_features(df)

        # 4. Handle Categorical / String Data (NEW FIX)
        # Drop high-cardinality and useless identifiers
        cols_to_drop = ['merchant', 'cc_num', 'first', 'last', 'street', 'city', 'state', 'zip', 'job', 'trans_num']
        existing_drops = [col for col in cols_to_drop if col in df.columns]
        df = df.drop(columns=existing_drops)

        # One-Hot Encode remaining low-cardinality categoricals
        cols_to_encode = [col for col in ['category', 'gender'] if col in df.columns]
        if cols_to_encode:
            df = pd.get_dummies(df, columns=cols_to_encode, drop_first=True)
            # Ensure boolean columns generated by get_dummies are converted to float/int for SMOTE
            for col in df.columns:
                if df[col].dtype == 'bool':
                    df[col] = df[col].astype(float)

        logging.info(f"Feature engineering complete. Output shape: {df.shape}")
        return df

if __name__ == "__main__":
    # Quick test to ensure compilation
    print("Feature Engineering module ready.")