apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: ghcr.io/mlflow/mlflow:latest
        ports:
        - containerPort: 5000
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom: { secretKeyRef: { name: aws-secrets, key: access-key } }
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom: { secretKeyRef: { name: aws-secrets, key: secret-key } }
        command: ["mlflow", "server"]
        args: [
          "--host", "0.0.0.0",
          "--port", "5000",
          "--backend-store-uri", "sqlite:///mlflow.db", # In prod, swap for postgres://
          "--default-artifact-root", "s3://wasim-fraud-mlops-artifacts/mlflow/"
        ]
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: mlflow
