project:
  name: "enterprise-fraud-detection"
  version: "1.0.0"

aws:
  s3_bucket_name: "wasim-fraud-mlops-data" # Replace with your unique bucket name later
  mlflow_artifact_path: "s3://wasim-fraud-mlops-artifacts/mlflow/"
  region: "ap-south-1"
data:
  raw_train_path: "data/raw/train.csv"
  raw_test_path: "data/raw/test.csv"
  processed_dir: "data/processed/"
  test_size: 0.2
  random_state: 42
  dev_mode: true
  dev_sample_size: 50000

model:
  target_column: "is_fraud"
  smote_sampling_strategy: 0.1
  xgb_params:
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 5
    scale_pos_weight: 10